Repository threeal/gcovr-action, pull requests merged in 2024-09, with the labels that each got.

#402 Unspecify Yarn Version in GitHub Workflows
  .github/workflows/build.yaml
  .github/workflows/check.yaml
Labels: ci

#404 Specify Node Version Using `.nvmrc` File
  .github/workflows/build.yaml
  .github/workflows/check.yaml
  .gitignore
  .nvmrc
Labels: build, ci

#413 Added option to generate report in html format and option to select one of gcovr predefined html theme
  .github/workflows/test.yaml
  README.md
  action.yml
  dist/index.js
  src/action.ts
  src/gcovr.ts
Labels: feat

#415 Specify Runner OS Version in Workflows
  .github/workflows/build.yaml
  .github/workflows/check.yaml
  .github/workflows/test.yaml
Labels: ci

#420 Bump Yarn to Version 4.5.0
  package.json
Labels: chore

#431 Added html-details and html-title inputs
  .github/workflows/test.yaml
  README.md
  action.yml
  dist/index.js
  src/action.ts
  src/gcovr.ts
Labels: feat

#433 Add options for failing on branch and function coverage
  .github/workflows/test.yaml
  README.md
  action.yml
  dist/index.js
  sample/include/is_even.hpp
  sample/include/is_odd.hpp
  src/action.ts
  src/gcovr.ts
Labels: feat

#436 Update Readme for Version 1.1.0 Release
  README.md
  action.yml
Labels: docs
