Repository threeal/gcovr-action, pull requests merged in 2025-01, with the labels that each got.

#515 Configure Dependabot Label to Empty
  .github/dependabot.yaml
Labels: ci

#518 Bump Yarn to Version 4.6.0
  package.json
Labels: chore

#520 Bump Copyright Year to 2025
  LICENSE
  README.md
Labels: docs

#524 Bump Node.js to version 23.6.0
  .nvmrc
Labels: chore

#526 Various improvements to gcovr-action
  README.md
  action.yml
  dist/index.js
  src/action.ts
  src/gcovr.ts
Labels: chore

#535 Update Distribution File
  dist/index.js
Labels: build
